// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/itaraxa/turbo-waddle/internal/storage (interfaces: BalanceStorager)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	log "github.com/itaraxa/turbo-waddle/internal/log"
	models "github.com/itaraxa/turbo-waddle/internal/models"
)

// MockBalanceStorager is a mock of BalanceStorager interface.
type MockBalanceStorager struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceStoragerMockRecorder
}

// MockBalanceStoragerMockRecorder is the mock recorder for MockBalanceStorager.
type MockBalanceStoragerMockRecorder struct {
	mock *MockBalanceStorager
}

// NewMockBalanceStorager creates a new mock instance.
func NewMockBalanceStorager(ctrl *gomock.Controller) *MockBalanceStorager {
	mock := &MockBalanceStorager{ctrl: ctrl}
	mock.recorder = &MockBalanceStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceStorager) EXPECT() *MockBalanceStoragerMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockBalanceStorager) GetBalance(arg0 context.Context, arg1 log.Logger, arg2 string) (models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceStoragerMockRecorder) GetBalance(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceStorager)(nil).GetBalance), arg0, arg1, arg2)
}
